gunslinger_Animation_List = ds_list_create();
ds_list_add(gunslinger_Animation_List, spr_Player_Gunslinger_Standing);
ds_list_add(gunslinger_Animation_List, spr_Player_Gunslinger_Running);
ds_list_add(gunslinger_Animation_List, spr_Player_Gunslinger_Standing);
ds_list_add(gunslinger_Animation_List, spr_Player_Gunslinger_Crouching);

animation_List = gunslinger_Animation_List;